name: Latest Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*'

permissions:
  contents: read

env:
  NW_VERSION: '0.112.0'

jobs:
  build:
    name: Build (${{ matrix.platform }})
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux64
          - os: macos-15-intel
            platform: osx64
          - os: macos-latest
            platform: osx-arm64
          - os: windows-latest
            platform: win64

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Use Node.js 20
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 20
          cache: yarn

      - name: Build info
        run: echo Build ${{ matrix.platform }} on nw-v${{ env.NW_VERSION }}

      - name: Build App
        run: |
          yarn install --frozen-lockfile
          yarn gulp dist --platforms=${{ matrix.platform }} --nwVersion=${{ env.NW_VERSION }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: ${{ matrix.platform }}-${{ env.NW_VERSION }}
          path: build
          if-no-files-found: error
          compression-level: 0

  packs:
    needs: build
    name: Packs
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
        with:
          path: repo
          persist-credentials: false

      - uses: actions/download-artifact@v8.0.1
        with:
          name: linux64-${{ env.NW_VERSION }}
          path: .

      - name: Install packages and appimagetool
        run: |
          sudo apt update
          sudo apt install -y libfuse2
          wget https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage
          chmod +x appimagetool-x86_64.AppImage

      - name: Build AppImage
        run: |
          VER=$(ls *-linux64*.zip | sed 's/-linux64.*//')
          echo $VER
          unzip -q *-linux64*.zip -d $VER.AppDir
          cp repo/dist/linux/appimage/* $VER.AppDir/
          ln -s Popcorn-Time $VER.AppDir/AppRun
          mkdir build
          ARCH=x86_64 ./appimagetool-x86_64.AppImage $VER.AppDir build/$VER-linux64.AppImage

      - name: Upload artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: linux64-${{ env.NW_VERSION }}.AppImage
          path: build
          if-no-files-found: error
          compression-level: 0

  release:
    if: startsWith(github.ref, 'refs/tags/v')
    needs: packs
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v8.0.1
        with:
          path: artifacts
          merge-multiple: true

      - uses: ncipollo/release-action@v1.20.0
        with:
          allowUpdates: true
          name: ${{ github.ref_name }}
          artifacts: 'artifacts/*'
